export const camposFormulario = [
  {
    type: 'select',
    label: 'Etapas',
    name: 'etapas',
    options: [
      { label: 'Emissão de OS', value: 1 },
      { label: 'Art', value: 2 },
      { label: 'Aba3', value: 3 },
      { label: 'Laudo de Estanquiadade', value: 4 },
      { label: 'Laudo de Aterramento', value: 5 },
      { label: 'Laudo de Limpeza', value: 6 },
      { label: 'Relatório de Instalação', value: 7 },
      { label: 'Relatório de Atendimento tecnico', value: 8 },
      { label: 'RAT manuscrito', value: 9 },
      { label: 'Projetos', value: 10 },
      { label: 'Guia de remessa de documentos', value: 12 },
      { label: 'NF/NFS', value: 13 },
      { label: 'Imagens', value: 14 },
      { label: 'Anexos', value: 15 },
      { label: 'Observações', value: 16 },
      { label: 'Avaliação', value: 17 },
    ],
  },
  {
    type: 'textArea',
    label: 'descricao',
    name: 'descricao',
  },
  {
    type: 'text',
    label: 'Prazo de Execução',
    name: 'prazo_execucao',
  },
  {
    type: 'text',
    label: 'Data Limite',
    name: 'data_limite',
  },
  {
    type: 'text',
    label: 'Materiais',
    name: 'data_limite',
  },
  {
    type: 'text',
    label: 'Data Limite',
    name: 'Ferramenta',
  },
];
